# Generated by Django 3.1.4 on 2021-03-05 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 5, 10, 11, 40, 452634, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
